[PR2] DEV-23 improve connection negotiation and cleanup
HyperloopUPV-H8/cs-frontend pull request #24
Opened 2023-04-08 09:45 UTC by jmaralo

The previous implementation was out of sync with the media server. This new version uses the onnegotiationneeded event to know when to exchange offer and answer through the singaling channel.

Some events have also been buffered in case they are triggered during an unappropiate moment during the handshake.

The WebRTC connection is now correclty cleaned up after use, which caused errors previously with react strict mode due to incorrect cleanup.

The package has been modified to expose the development build on the network to make testing of the cameras page easier.

2023-04-08 10:00 UTC, smorsua commented on src/hooks/WebRTC/RemotePeer.ts
> +    constructor(signalAddr: string, configuration?: RTCConfiguration) {
Remove configuration if not needed

2023-04-08 10:00 UTC, smorsua commented on src/hooks/WebRTC/SignalChannel.ts
> +        this.socket.onclose = () => {
The onclose and the onerror and not necessary

2023-04-08 10:00 UTC, smorsua commented on src/hooks/WebRTC/signal.ts
> +export enum SignalCode {
Make strings instead of numbers

2023-04-08 10:00 UTC, smorsua commented on src/pages/CamerasPage/CamerasPage.tsx
> +    const [streams, state] = useWebRTC(import.meta.env.VITE_CAMERA_1_URL);
Change env variable name to `VITE_CAMERAS_URL`

2023-04-08 10:04 UTC, smorsua approved these changes

2023-04-08 10:35 UTC, Losina24 commented on src/hooks/WebRTC/RemotePeer.ts
> +        if (!ev.candidate) {
if (!ev.candidate) return

2023-04-08 10:51 UTC, Losina24 requested changes, later dismissed

2023-04-08 10:51 UTC, Losina24 commented on src/hooks/WebRTC/RemotePeer.ts
> +    private async onCandidateSignal(signal: Signal<"candidate">) {
u have to try to remove this ifs with a lot of or clauses
```ts
private async onCandidateSignal (signal: Signal<"candidate">) {
    if (isCandidate()) return this.candidateBuffer.push(signal.payload)
    await this.peer.addIceCandidate(signal.payload)
}

private isCandidate() {
    const candidateStates = new Set(["stable", "have-remote-offer", "have-remote-pranswer"])
    return candidateStates.map(this.peer.signalingState)
}
```

2023-04-08 10:51 UTC, Losina24 commented on src/hooks/WebRTC/RemotePeer.ts
> +        if (this.peer.signalingState !== "stable" && this.peer.signalingState !== "have-remote-offer" && this.peer.signalingState !== "have-remote-pranswer") {
same here

2023-04-08 10:51 UTC, Losina24 commented on src/hooks/WebRTC/RemotePeer.ts
> +        if (this.peer.signalingState !== "stable" && this.peer.signalingState !== "have-remote-offer" && this.peer.signalingState !== "have-remote-pranswer") {
to reuse the Set, u can declare outside the first function and use it in both functions

2023-04-09 11:00 UTC, lipezaballa approved these changes

2023-04-09 19:01 UTC, merged